//2         SPACES
hexingPants             									hexing-pants-of-mr-yan
taskerAndTheo           									tasker-and-theo
theFurnace              									the-furnace
immortalKingSet         									immortal-kings-boulder-breaker
ancientParthanDefenders 									ancient-parthan-defenders
theGravelOfJudgement    									the-gavel-of-judgment
strongarmBracers        									strongarm-bracers
lacuniProwlers          									lacuni-prowlers
bulKathosSet            									bulkathoss-warrior-blood
leoricCrown             									leorics-crown
rolandSet               									rolands-visage
bloodBrother            									blood-brother
skywarden               									skywarden
goldenFlense            									golden-flense
denial                  									denial
cindercoat              									cindercoat
thunderfury             									thunderfury-blessed-blade-of-the-windseeker
calamity                									calamity
unhallowedEssenceSet    									accursed-visage
deadManLegacy           									dead-mans-legacy
natalyaSet              									natalyas-sight
balefireCaster          									balefire-caster
flyingDragon            									flying-dragon
depthDiggers            									depth-diggers
spiritGuards            									spirit-guards
mageFist                									magefist
eyeOfPeshkov            									eye-of-peshkov
theCrudestBoots         									the-crudest-boots
shenlongSet             									shenlongs-fist-of-legend
innaSet                 									innas-vast-expanse
raimentSet              									mask-of-the-searing-sky
starmetalKukri          									starmetal-kukri
maskOfJeram             									mask-of-jeram
theGrinReaper           									the-grin-reaper
carnevil                									carnevil
thingOfTheDeep          									thing-of-the-deep
daggerOfDarts           									the-dagger-of-darts
aughildShoulders        									ughilds-power
aughildBracers          									ughilds-search
zunimassaSet            									zunimassas-marrow
helltoothSet            									helltooth-tunic
theGrandVizier          									the-grand-vizier
nilfurBoast             									nilfurs-boast
crownOfThePrimus        									crown-of-the-primus
aetherWalker            									aether-walker
sunKeeper               									sun-keeper
gestureOfOrpheus        									gesture-of-orpheus
ranslorFolly            									ranslors-folly
serpentSparker          									serpents-sparker
talRashaSet             									tal-rashas-unwavering-glare
delsereSet              									shrouded-mask

//1         SPACE
lamentation             									lamentation
obsidianRingOfTheZodiac 									obsidian-ring-of-the-zodiac
RingOfRoyalGrandeur     									ring-of-royal-grandeur-3qRFop
unity                   									unity
conventionOfElements    									convention-of-elements
focusRestraintSet       									restraint
prideOfCassius          									pride-of-cassius
thundergodVigor         									thundergods-vigor
stringOfEars            									string-of-ears
theWitchingHour         									the-witching-hour
vigilanteBelt           									vigilante-belt
crashingRain            									crashing-rain
beltOfTranscendence     									belt-of-transcendence



//IMPORTANT ITEMS
bovineBardiche          									bovine-bardiche
puzzleRing              									puzzle-ring